services:
  digestBot:
    image: digest-bot-app
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data